# Generated by Django 2.2.2 on 2019-06-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='data/no-img.jpg', upload_to='data/'),
        ),
    ]
