# Generated by Django 2.2.2 on 2019-06-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190610_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.CharField(default='img1.jpg', max_length=150),
            preserve_default=False,
        ),
    ]
