# Generated by Django 2.2.2 on 2019-06-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='gallery.Image'),
        ),
    ]
