# Generated by Django 2.2.2 on 2019-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20190611_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='showcase_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
