# Generated by Django 2.2.2 on 2019-06-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_collection_showcase_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='images',
            field=models.ManyToManyField(blank=True, to='gallery.Image'),
        ),
    ]
