# Generated by Django 2.2.2 on 2019-06-19 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_collection_permitted_users'),
        ('blog', '0002_auto_20190619_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='gallery.Image'),
            preserve_default=False,
        ),
    ]
